# Bit manipulation #389: Find the difference

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# Examples:
# s1 = "abcd", t1 = "abcde" --> e
# s2 = "", t2 = "y" --> y
# s3 = "a", t3 = "aa" --> a


# Time: O(N), Space: O(1)
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        n = len(t)
        missing = ord(t[n - 1])
        for i in range(n - 1):
            sCode, tCode = ord(s[i]), ord(t[i])
            missing ^= sCode ^ tCode
        return chr(missing)


s1, t1 = "koli", "kiglo"
